puml
@startuml
title WarmHouse Context Diagram

top to bottom direction

!include ../c4/C4_Context.puml

Person_Ext(User, "User", "Пользователь системы:\n— Подключает устройства\n— Настраивает сценарии\n— Просматривает телеметрию")
Person(Support, "Support", "Специалист поддержки:\n— Консультирует пользователей\n— Решает технические инциденты")

System(WarmHouseSystem, "WarmHouse System", "Система управления тёплым домом")

System_Ext(WarmSensor, "Warm Sensor", "Датчик управления отоплением", "Uses HTTP API, MQTT")
System_Ext(DoorSensor, "Door Sensor", "Датчик управления дверями", "Uses HTTP API, MQTT")
System_Ext(LightSensor, "Light Sensor", "Датчик управления светом", "Uses HTTP API, MQTT")
System_Ext(VideoSensor, "Video Sensor", "Датчик управления видеонаблюдением", "Uses HTTP API, MQTT")
System_Ext(UniversalSensor, "Universal Sensor", "Универсальный датчик умного дома", "Uses HTTP API, MQTT")

Rel(User, WarmHouseSystem, "Управляет отоплением, просматривает температуру")
Rel(Support, WarmHouseSystem, "Подключает новые датчики, осуществляет поддержку пользователей")

Rel(WarmHouseSystem, WarmSensor, "Команды управления отоплением\nПолучение данных о температуре", "MQTT/HTTP")
Rel(WarmHouseSystem, DoorSensor, "Команды управления воротами\nПолучение данных о состоянии ворот", "MQTT/HTTP")
Rel(WarmHouseSystem, LightSensor, "Команды управления светом\nПолучение данных о состоянии освещения", "MQTT/HTTP")
Rel(WarmHouseSystem, VideoSensor, "Команды управления видеонаблюдением\nПолучение данных о состоянии видеонаблюдения", "MQTT/HTTP")
Rel(WarmHouseSystem, UniversalSensor, "Команды управления универсальным модулем\nПолучение данных о состоянии универсального датчика", "MQTT/HTTP")

@enduml