@startuml WarmHouse_Container_TelemetryDomain
title WarmHouse Container Diagram (Telemetry Domain)

top to bottom direction

!include ../c4/C4_Container.puml

skinparam wrapWidth 300
skinparam linetype polyline

System_Boundary(WarmHouseSystem, "WarmHouse System") {
    Container_Boundary(UserInterfacesDomain, "Пользовательские интерфейсы") {
        Container(BackendForFrontend, "Application Backend", "Node.JS", "")
    }

    Container_Boundary(DeviceDomain, "Управление устройствами") {
        Container_Boundary(DeviceIntegrationDomain, "Взаимодействие с устройствами") {
            Container(DeviceTelemetryConnector, "Device Telemetry Connector", "Go", "Сбор и получение телеметрии подключенных устройств") 
        }
    }
  
    Container_Boundary(TelemetryDomain, "Телеметрия устройств") {
        Container(TelemetryProcessingService, "Telemetry Processing Service", "Go", "Обработка показателей телеметрии устройств")
        Container(TelemetryDashboardService, "Telemetry Dashboard Service", "Go", "Предоставление различной информации о телеметрии в различных срезах")
        ContainerQueue(TelemetryQueueService, "Telemetry Queue", "RabbitMQ", "Доставка показателей телеметрии")
        ContainerDb(TelemetryDatabase, "Telemetry Database", "ClickHouse", "Хранение данных о телеметрии устройств")

        Rel(TelemetryQueueService, TelemetryProcessingService, "Обработка потока телеметрии")
        Rel(TelemetryProcessingService, TelemetryDatabase, "Запись показателей телеметрии")
        Rel(TelemetryDashboardService, TelemetryDatabase, "Чтение показателей телеметрии")
    }
}

' Поддомен TelemetryDomain
Rel(DeviceTelemetryConnector, TelemetryQueueService, "Телеметрия устройства отопления")

' Поддомен UserInterfacesDomain
Rel(BackendForFrontend, TelemetryDashboardService, "Дашборды телеметрии устройств")

@enduml