@startuml WarmHouse_Container_DeviceIntegrationDomain
title WarmHouse Container Diagram (Device Integration Domain)

!include ../c4/C4_Container.puml

skinparam wrapWidth 300
skinparam linetype polyline

Boundary(Devices, "Devices") {
    System_Ext(WarmDevice, "Warm Device", "Датчик управления отоплением", "Uses HTTP API, MQTT")
    System_Ext(LightDevice, "Light Device", "Датчик управления светом", "Uses HTTP API, MQTT")
    System_Ext(DoorDevice, "Door Device", "Датчик управления воротами", "Uses HTTP API, MQTT")
    System_Ext(UniversalDevice, "Universal Device", "Универсальный датчик управления", "Uses HTTP API, MQTT")

    Lay_D(WarmDevice, LightDevice)
    Lay_D(LightDevice, DoorDevice)
    Lay_D(DoorDevice, UniversalDevice)
}

System_Boundary(WarmHouseSystem, "WarmHouse System") {
    Container_Boundary(DeviceDomain, "Управление устройствами") {
        Container_Boundary(UserDeviceDomain, "Устройства пользователя") {
            Container(DeviceManagementService, "Device Management Service", "Go", "Подключение и отключение устройств различных типов, предоставление информации о подключенных устройствах")
        }
    
        Container_Boundary(DeviceIntegrationDomain, "Управление отоплением") {
            Container(DeviceAPIService, "Device API Service", "Go", "Приём команд включения/выключения и установки значений параметров устройств") 
            ContainerQueue(DeviceQueue, "Device Queue", "RabbitMQ", "Организация асинхронной доставки команд устройству")
            ContainerDb(DeviceCache, "Device Cache", "Redis", "Кэширование параметров подключения к устройствам")
            Container(DeviceConnector, "Device Connector", "Go", "Передача устройству команд включения/выключения и установки параметров")
            Container(DeviceTelemetryConnector, "Device Telemetry Connector", "Go", "Сбор и получение телеметрии подключенных устройств")      
            
            Rel(DeviceAPIService, DeviceCache, "Запись параметров подключения к устройствам")
            Rel(DeviceAPIService, DeviceQueue, "Запись команд на отправку устройствам")
            Rel_U(DeviceConnector, DeviceCache, "Чтение параметров подключения к устройствам")
            Rel(DeviceTelemetryConnector, DeviceCache, "Чтение параметров подключения к устройствам")
            Rel(DeviceQueue, DeviceConnector, "Чтение команд на отправку устройствам")
        }
    }

    Container_Boundary(ScenarioDomain, "Сценарии устройств") {
        Container_Boundary(ScenarioProcessingDomain, "Выполнение сценариев") {
            Container(ScenarioProcessingService, "Scenario Processing Service", "Go", "Выполнение workflow сценария") 
            ContainerQueue(ScenarioQueueService, "Scenario Queue", "RabbitMQ", "Асинхронное получение потока телеметрии для запуска триггеров по условию")
        }
    }
  
    Container_Boundary(TelemetryDomain, "Телеметрия устройств") {
        ContainerQueue(TelemetryQueueService, "Telemetry Queue", "RabbitMQ", "Доставка показателей телеметрии")
    }
}

' Взаимодействие с внешними устройствами
Rel(DeviceConnector, Devices, "Отправка команд устройству")
Rel(DeviceTelemetryConnector, Devices, "Сбор телеметрии с устройства")
Rel(Devices, DeviceTelemetryConnector, "Получение телеметрии от устройства")

' Поддомен Device
Rel_L(DeviceAPIService, DeviceManagementService, "Получение параметров устройств")

' Поддомен ScenarioProcessingDomain
Rel_U(DeviceTelemetryConnector, ScenarioQueueService, "Телеметрия устройства отопления")
Rel_D(ScenarioProcessingService, DeviceAPIService, "Команды устройству отопления")

' Поддомен TelemetryDomain
Rel_U(DeviceTelemetryConnector, TelemetryQueueService, "Телеметрия устройства отопления")


@enduml