@startuml WarmHouse_Container_ScenarioProcessingDomain
title WarmHouse Container Diagram (Scenario Processing Domain)

top to bottom direction

!include ../c4/C4_Container.puml

skinparam wrapWidth 300
skinparam linetype polyline

System_Boundary(WarmHouseSystem, "WarmHouse System") {
    Container_Boundary(UserInterfacesDomain, "Пользовательские интерфейсы") {
        Container(BackendForFrontend, "Application Backend", "Node.JS", "")
    }

    Container_Boundary(DeviceDomain, "Управление устройствами") {
        Container_Boundary(DeviceIntegrationDomain, "Взаимодействие с устройствами") {
            Container(DeviceAPIService, "Device API Service", "Go", "Приём команд включения/выключения и установки значений параметров устройств") 
            Container(DeviceTelemetryConnector, "Device Telemetry Connector", "Go", "Сбор и получение телеметрии подключенных устройств") 

            Lay_D(DeviceTelemetryConnector, DeviceAPIService)
        }
    }

    Container_Boundary(ScenarioDomain, "Сценарии устройств") {
        Container_Boundary(ScenarioManagementDomain, "Управление сценариями") {
            Container(ScenarioWorkflowService, "Scenario Workflow Service", "Go", "Настройка workflow выполнения сценария")
        }

        Container_Boundary(ScenarioProcessingDomain, "Выполнение сценариев") {
            Container(ScenarioTriggerService, "Scenario Trigger Service", "Go", "Генерация триггеров для запуска сценариев (команды пользователя, телементрия устройств)")
            Container(ScenarioProcessingService, "Scenario Processing Service", "Go", "Выполнение workflow сценария")
            ContainerDb(ScenarioCacheDatabase, "Scenario Cache", "Redis", "Хранение состояния выполнения запущенных процессов")
            ContainerQueue(ScenarioQueueService, "Scenario Queue", "RabbitMQ", "Асинхронное получение потока телеметрии для запуска триггеров по условию")

            Rel_D(ScenarioTriggerService, ScenarioCacheDatabase, "Чтение/Запись триггеров активных сценариев")
            Rel_U(ScenarioProcessingService, ScenarioCacheDatabase, "Чтение/Запись состояния запущенных процессов")

            Rel(ScenarioQueueService, ScenarioTriggerService, "Асинхронное получение телеметрии устройств")
            Rel(ScenarioTriggerService, ScenarioProcessingService, "Передача данных о срабатывании триггера")     
        }
    }
}

' Поддомен ScenarioManagementDomain
Rel_L(ScenarioProcessingService, ScenarioWorkflowService, "Получение настроек workflow сценариев")
Rel_L(ScenarioTriggerService, ScenarioWorkflowService, "Получение параметров триггеров в workflow сценариев")

' Поддомен ScenarioProcessingDomain
Rel(DeviceTelemetryConnector, ScenarioQueueService, "Телеметрия устройства отопления")
Rel_R(ScenarioProcessingService, DeviceAPIService, "Команды устройству отопления")

' Поддомен UserInterfacesDomain
Rel(BackendForFrontend, ScenarioTriggerService, "Команды запуска сценариев устройств")

@enduml