@startuml WarmHouse_Container_ToBe
title WarmHouse Container Diagram

top to bottom direction

!include ../c4/C4_Container.puml

skinparam wrapWidth 300
skinparam linetype polyline

Person_Ext(User, "User", "Пользователь системы")
Person(Support, "Support", "Специалист поддержки")

Boundary(Devices, "Devices") {
    System_Ext(WarmDevice, "Warm Device", "Датчик управления отоплением", "Uses HTTP API, MQTT")
    System_Ext(LightDevice, "Light Device", "Датчик управления светом", "Uses HTTP API, MQTT")
    System_Ext(DoorDevice, "Door Device", "Датчик управления воротами", "Uses HTTP API, MQTT")
    System_Ext(UniversalDevice, "Universal Device", "Универсальный датчик управления", "Uses HTTP API, MQTT")

    Lay_D(WarmDevice, LightDevice)
    Lay_D(LightDevice, DoorDevice)
    Lay_D(DoorDevice, UniversalDevice)
}

System_Boundary(WarmHouseSystem, "WarmHouse System") {
    Container_Boundary(UserInterfacesDomain, "Пользовательские интерфейсы") {
        Container(WebApp, "Web Application", "Angular, Node.JS", "Web-интерфейс для работы с системой")
        Container(MobileApp, "Mobile Application", "Kotlin, Swift", "Мобильное приложение для работы с системой")
        Container(BackendForFrontend, "Application Backend", "Node.JS", "")
        Container(UserService, "User Service", "Node.JS", "Регистрация пользователей и управление профилем")
        Container(AuthService, "Auth Service", "Node.JS", "Аутентификация и авторизация в системе")
        ContainerDb(UsersDatabase, "Users Database", "PostgreSQL", "Хранение данных о пользователях системы")
        
        Rel(WebApp, BackendForFrontend, "", "https")
        Rel(MobileApp, BackendForFrontend, "", "https")
        Rel(BackendForFrontend, UserService, "Получение данных профиля пользователей", "https")
        Rel(BackendForFrontend, AuthService, "Авторизация пользователей", "https")        
        Rel(UserService, UsersDatabase, "Чтение/запись данных пользователя")
        Rel(AuthService, UsersDatabase, "Чтение данных пользователя для авторизации")
    }

    Container_Boundary(DeviceDomain, "Управление устройствами") {
        Container_Boundary(UserDeviceDomain, "Устройства пользователя") {
            Container(DeviceManagementService, "Device Management Service", "Go", "Подключение и отключение устройств различных типов, предоставление информации о подключенных устройствах")
            ContainerDb(DeviceDatabase, "Device Database", "PostgreSQL", "Хранение данных о подключенных устройствах пользователей")

            Rel(DeviceManagementService, DeviceDatabase, "Чтение/запись данных устройств")
        }
    
        Container_Boundary(DeviceIntegrationDomain, "Взаимодействие с устройствами") {
            Container(DeviceAPIService, "Device API Service", "Go", "Приём команд включения/выключения и установки значений параметров устройств") 
            ContainerQueue(DeviceQueue, "Device Queue", "RabbitMQ", "Организация асинхронной доставки команд устройству")
            ContainerDb(DeviceCache, "Device Cache", "Redis", "Кэширование параметров подключения к устройствам")
            Container(DeviceConnector, "Device Connector", "Go", "Передача устройству команд включения/выключения и установки параметров")
            Container(DeviceTelemetryConnector, "Device Telemetry Connector", "Go", "Сбор и получение телеметрии подключенных устройств") 
            
            Rel(DeviceAPIService, DeviceCache, "Запись параметров подключения к устройствам")
            Rel(DeviceAPIService, DeviceQueue, "Запись команд на отправку устройствам")
            Rel(DeviceConnector, DeviceCache, "Чтение параметров подключения к устройствам")
            Rel(DeviceTelemetryConnector, DeviceCache, "Чтение параметров подключения к устройствам")
            Rel(DeviceQueue, DeviceConnector, "Чтение команд на отправку устройствам")   
        }
    }

    Container_Boundary(ScenarioDomain, "Сценарии устройств") {
        Container_Boundary(ScenarioManagementDomain, "Управление сценариями") {
            Container(ScenarioService, "Scenario Service", "Go", "Создание, удаление и управление активностью сценария, предоставление информации о сценариях пользователя")
            Container(ScenarioWorkflowService, "Scenario Workflow Service", "Go", "Настройка workflow выполнения сценария")
            ContainerDb(ScenarioDatabase, "Scenario Database", "PostgreSQL", "Хранение данных о сценариях и настройках их workflow")
            
            Rel(ScenarioService, ScenarioDatabase, "Чтение/Запись сценариев")
            Rel(ScenarioWorkflowService, ScenarioDatabase, "Чтение/Запись настроек workflow сценариев")
        }

        Container_Boundary(ScenarioProcessingDomain, "Выполнение сценариев") {
            Container(ScenarioTriggerService, "Scenario Trigger Service", "Go", "Генерация триггеров для запуска сценариев (команды пользователя, телементрия устройств)")
            Container(ScenarioProcessingService, "Scenario Processing Service", "Go", "Выполнение workflow сценария")
            ContainerDb(ScenarioCacheDatabase, "Scenario Cache", "Redis", "Хранение состояния выполнения запущенных процессов")
            ContainerQueue(ScenarioQueueService, "Scenario Queue", "RabbitMQ", "Асинхронное получение потока телеметрии для запуска триггеров по условию")

            Rel(ScenarioTriggerService, ScenarioCacheDatabase, "Чтение/Запись триггеров активных сценариев")
            Rel(ScenarioProcessingService, ScenarioCacheDatabase, "Чтение/Запись состояния запущенных процессов")

            Rel(ScenarioQueueService, ScenarioTriggerService, "Асинхронное получение телеметрии устройств")
            Rel(ScenarioTriggerService, ScenarioProcessingService, "Передача данных о срабатывании триггера")     
        }
    }
  
    Container_Boundary(TelemetryDomain, "Телеметрия устройств") {
        Container(TelemetryProcessingService, "Telemetry Processing Service", "Go", "Обработка показателей телеметрии устройств")
        Container(TelemetryDashboardService, "Telemetry Dashboard Service", "Go", "Предоставление различной информации о телеметрии в различных срезах")
        ContainerQueue(TelemetryQueueService, "Telemetry Queue", "RabbitMQ", "Доставка показателей телеметрии")
        ContainerDb(TelemetryDatabase, "Telemetry Database", "ClickHouse", "Хранение данных о телеметрии устройств")

        Rel(TelemetryQueueService, TelemetryProcessingService, "Обработка потока телеметрии")
        Rel(TelemetryProcessingService, TelemetryDatabase, "Запись показателей телеметрии")
        Rel(TelemetryDashboardService, TelemetryDatabase, "Чтение показателей телеметрии")
    }
}

' Взаимодействие пользователей с системой
Rel(User, WebApp, "Подключает и управляет новыми устройствами, Настраивает сценарии, Просматривает телеметрию")
Rel(User, MobileApp, "Подключает и управляет новыми устройствами, Настраивает сценарии, Просматривает телеметрию")
Rel(Support, WebApp, "Осуществляет поддержку пользователей")

' Взаимодействие с внешними устройствами
Rel(DeviceConnector, Devices, "Отправка команд устройству")
Rel(DeviceTelemetryConnector, Devices, "Сбор телеметрии с устройства")
Rel(Devices, DeviceTelemetryConnector, "Получение телеметрии от устройства")

' Поддомен Device
Rel(DeviceAPIService, DeviceManagementService, "Получение параметров устройств")

' Поддомен ScenarioManagementDomain
Rel(ScenarioWorkflowService, DeviceManagementService, "Получение параметров устройств")
Rel(ScenarioProcessingService, ScenarioWorkflowService, "Получение настроек workflow сценариев")
Rel(ScenarioTriggerService, ScenarioWorkflowService, "Получение параметров триггеров в workflow сценариев")

' Поддомен ScenarioProcessingDomain
Rel(DeviceTelemetryConnector, ScenarioQueueService, "Телеметрия устройства отопления")
Rel(ScenarioProcessingService, DeviceAPIService, "Команды устройству отопления")

' Поддомен TelemetryDomain
Rel(DeviceTelemetryConnector, TelemetryQueueService, "Телеметрия устройства отопления")

' Поддомен UserInterfacesDomain
Rel(BackendForFrontend, TelemetryDashboardService, "Дашборды телеметрии устройств")
Rel(BackendForFrontend, DeviceManagementService, "Команды настройки устройств пользователя")
Rel(BackendForFrontend, ScenarioService, "Команды создания/редактирования сценариев устройств")
Rel(BackendForFrontend, ScenarioWorkflowService, "Команды настройки сценариев устройств")
Rel(BackendForFrontend, ScenarioTriggerService, "Команды запуска сценариев устройств")

@enduml