@startuml WarmHouse_Container_ToBe
title WarmHouse Container Diagram

top to bottom direction

!include ../c4/C4_Container.puml

System_Ext(WarmDevice, "Warm Device", "Датчик управления отоплением", "Uses HTTP API, MQTT")

System_Boundary(WarmHouseSystem, "WarmHouse System") {
  Container_Boundary(DeviceDomain, "Управление устройствами") {
    Container_Boundary(WarmDeviceDomain, "Управление отоплением") {
        Container(WarmConnector, "Warm Connector", "Go", "Передача командды установки параметров отопления устройству")
        Container(WarmTelemetryConnector, "Warm Telemetry Connector", "Go", "Сбор и получение телеметрии устройства отопления")
        ContainerQueue(WarmQueue, "Warm Queue", "RabbitMQ", "Организация асинхронной доставки команд устройству")
        Container(WarmService, "Warm Service", "Go", "Приём команды установки значений параметров устройства отопления") 
        ContainerDb(WarmCache, "Warm Cache", "Redis", "Кэширование параметров подключения к устройствам")

        Rel_R(WarmService, WarmCache, "Запись параметров подключения к устройствам")
        Rel_R(WarmConnector, WarmCache, "Чтение параметров подключения к устройствам")
        Rel_R(WarmTelemetryConnector, WarmCache, "Чтение параметров подключения к устройствам")
        Rel_R(WarmService, WarmQueue, "Запись команд на отправку устройствам")
        Rel_R(WarmQueue, WarmConnector, "Чтение команд на отправку устройствам")

        Lay_D(WarmConnector, WarmTelemetryConnector)
    }
  }
}

' Взаимодействие с внешними устройствами
Rel_R(WarmConnector, WarmDevice, "Отправка команд устройству")
BiRel_R(WarmTelemetryConnector, WarmDevice, "Сбор и получение телеметрии устройства")

@enduml