@startuml WarmHouse_Container_ToBe
title WarmHouse Container Diagram (User Device Domain)

top to bottom direction

!include ../c4/C4_Container.puml

skinparam wrapWidth 300
skinparam linetype polyline

System_Boundary(WarmHouseSystem, "WarmHouse System") {
    Container_Boundary(UserInterfacesDomain, "Интерфейсы системы") {
        Container(BackendForFrontend, "Application Backend", "Node.JS", "")
    }

    Container_Boundary(DeviceDomain, "Управление устройствами") {
        Container_Boundary(UserDeviceDomain, "Устройства пользователя") {
            Container(DeviceManagementService, "Device Management Service", "Go", "Подключение и отключение устройств различных типов, предоставление информации о подключенных устройствах")
            ContainerDb(DeviceDatabase, "Device Database", "PostgreSQL", "Хранение данных о подключенных устройствах пользователей")

            Rel(DeviceManagementService, DeviceDatabase, "Чтение/запись данных устройств")
        }
    
        Container_Boundary(DeviceIntegrationDomain, "Взаимодействие с устройствами") {
            Container(DeviceAPIService, "Device API Service", "Go", "Приём команды установки значений параметров устройства отопления") 
        }
    }

    Container_Boundary(ScenarioDomain, "Сценарии устройств") {
        Container_Boundary(ScenarioManagementDomain, "Управление сценариями") {
            Container(ScenarioWorkflowService, "Scenario Workflow Service", "Go", "Настройка workflow выполнения сценария")
        }
    }
}

' Поддомен Device
Rel(DeviceAPIService, DeviceManagementService, "Получение параметров устройств")

' Поддомен ScenarioManagementDomain
Rel(ScenarioWorkflowService, DeviceManagementService, "Получение параметров устройств")

' Поддомен UserInterfacesDomain
Rel(BackendForFrontend, DeviceManagementService, "Команды настройки устройств пользователя")

@enduml