@startuml Component_DeviceConnector
title WarmHouse: Device Connector Component Diagram

!includeurl ../c4/C4_Component.puml

Container_Boundary(DeviceIntegrationDomain, "Взаимодействие с устройствами") {
  ContainerQueue(DeviceQueue, "Device Queue", "RabbitMQ", "Организация асинхронной доставки команд устройству")          
  ContainerDb(DeviceCache, "Device Cache", "Redis", "Кэширование параметров подключения к устройствам")
  Container(DeviceConnector, "Device Connector", "Go", "Передача устройству команд включения/выключения и установки параметров")
}

Container(DeviceConnector, "Device Connector", "Go") {
  Component(QueueDeliveryLayer, "Queue Delivery Layer", "Чтение потока команд из очереди RabbitMQ")
  Component(RepositoryLayer, "Repository Layer", "Чтение параметров подключения из базы данных")
  Component(ServiceLayer, "Service Layer", "Логика обработки команд")

  Component(WarmDeviceConnector, "WarmDeviceConnector", "Коннектор к устройствам управления отоплением")
  Component(LightDeviceConnector, "LightDeviceConnector", "Коннектор к устройствам управления светом")
  Component(DoorDeviceConnector, "DoorDeviceConnector", "Коннектор к устройствам управления воротами")
  Component(UniversalDeviceConnector, "UniversalDeviceConnector", "Коннектор к универсальным устройствам")

  Rel(QueueDeliveryLayer, ServiceLayer, "Передача команды из очереди на обработку")
  Rel(ServiceLayer, RepositoryLayer, "Получение параметров подключения")
  Rel(ServiceLayer, WarmDeviceConnector, "Отправка команды устройству")
  Rel(ServiceLayer, LightDeviceConnector, "Отправка команды устройству")
  Rel(ServiceLayer, DoorDeviceConnector, "Отправка команды устройству")
  Rel(ServiceLayer, UniversalDeviceConnector, "Отправка команды устройству")
}

Rel(QueueDeliveryLayer, DeviceQueue, "Чтение сообщений из очереди")
Rel(RepositoryLayer, DeviceCache, "Чтение параметров подключения")

@enduml